#!/bin/with-contenv bash

# This script runs inside the container on startup
TEST_MODE="${TEST_MODE:-true}"
SSH_DIR="/config/.ssh"
OBSIDIAN_CONFIG_DIR="/config/.config/obsidian"
OBSIDIAN_JSON="$OBSIDIAN_CONFIG_DIR/obsidian.json"

# 1. Setup SSH if a private key is provided
if [ -n "$SSH_PRIVATE_KEY" ] && [ ! -f "$SSH_DIR/id_rsa" ]; then
    echo "**** Setting up SSH key... ****"
    mkdir -p "$SSH_DIR"
    if [[ "$SSH_PRIVATE_KEY" == LS0tLS1* ]]; then
        echo "$SSH_PRIVATE_KEY" | base64 -d > "$SSH_DIR/id_rsa"
    else
        echo "$SSH_PRIVATE_KEY" > "$SSH_DIR/id_rsa"
    fi
    chmod 600 "$SSH_DIR/id_rsa"
    lsiown -R abc:abc "$SSH_DIR"
    ssh-keyscan github.com >> "$SSH_DIR/known_hosts"
    lsiown abc:abc "$SSH_DIR/known_hosts"
fi

# 2. Vault Logic
if [ "$TEST_MODE" = "true" ]; then
    VAULT_PATH="/vaults/test-vault"
    VAULT_ID_FILE="/config/.vault_id_test"
    if [ -f "$VAULT_ID_FILE" ]; then
        VAULT_ID=$(cat "$VAULT_ID_FILE")
    else
        VAULT_ID=$(head /dev/urandom | tr -dc 'a-f0-9' | head -c 16)
        echo "$VAULT_ID" > "$VAULT_ID_FILE"
    fi
    
    if [ ! -d "$VAULT_PATH/.obsidian" ]; then
        echo "**** TEST_MODE=true: Seeding isolated dummy vault at $VAULT_PATH (ID: $VAULT_ID) ****"
        mkdir -p "$VAULT_PATH/.obsidian/plugins/obsidian-local-rest-api"
        echo '{"pluginEnabled": true, "community-plugin-v2": true, "nativeMenus": false, "useTitleBar": false}' > "$VAULT_PATH/.obsidian/app.json"
        echo '["obsidian-local-rest-api"]' > "$VAULT_PATH/.obsidian/community-plugins.json"
        
        echo "**** Downloading Local REST API plugin... ****"
        curl -L -s -o "$VAULT_PATH/.obsidian/plugins/obsidian-local-rest-api/main.js" "https://github.com/coddingtonbear/obsidian-local-rest-api/releases/latest/download/main.js"
        curl -L -s -o "$VAULT_PATH/.obsidian/plugins/obsidian-local-rest-api/manifest.json" "https://github.com/coddingtonbear/obsidian-local-rest-api/releases/latest/download/manifest.json"
        echo "{\"apiKey\":\"$OBSIDIAN_API_KEY\",\"bindAddress\":\"127.0.0.1\",\"port\":27123,\"enableInsecureServer\":true}" > "$VAULT_PATH/.obsidian/plugins/obsidian-local-rest-api/data.json"
        
        if [ ! -f "$VAULT_PATH/Welcome.md" ]; then
            echo "# Welcome to Test Vault\n\nThis is an isolated vault for API testing." > "$VAULT_PATH/Welcome.md"
        fi
    fi
else
    VAULT_PATH="/vaults/real-vault"
    VAULT_ID_FILE="/config/.vault_id_real"
    if [ -f "$VAULT_ID_FILE" ]; then
        VAULT_ID=$(cat "$VAULT_ID_FILE")
    else
        VAULT_ID=$(head /dev/urandom | tr -dc 'a-f0-9' | head -c 16)
        echo "$VAULT_ID" > "$VAULT_ID_FILE"
    fi
    echo "**** TEST_MODE=false: Using real vault at $VAULT_PATH (ID: $VAULT_ID) ****"
    
    if [ ! -d "$VAULT_PATH/.git" ]; then
        if [ -n "$GIT_REPO_URL" ] && [ -n "$SSH_PRIVATE_KEY" ]; then
            echo "**** Cloning real vault from $GIT_REPO_URL... ****"
            sudo -u abc git clone "$GIT_REPO_URL" "$VAULT_PATH"
        else
            echo "**** ERROR: TEST_MODE=false but GIT_REPO_URL or SSH_PRIVATE_KEY missing! ****"
        fi
    fi
fi

# 3. Ensure Obsidian config exists
if [ ! -f "$OBSIDIAN_JSON" ]; then
    mkdir -p "$OBSIDIAN_CONFIG_DIR"
    mkdir -p "/config/.config/openbox"
    CONFIG_CONTENT="{\"vaults\":{\"$VAULT_ID\":{\"path\":\"$VAULT_PATH\",\"ts\":$(date +%s%3N),\"open\":true,\"trusted\":true}},\"lastOpenedVault\":\"$VAULT_ID\"}"
    echo "$CONFIG_CONTENT" > "$OBSIDIAN_JSON"
    echo "{}" > "$OBSIDIAN_CONFIG_DIR/$VAULT_ID.json"

    # Fix the Obsidian wrapper to include the vault path
    if [ "$TEST_MODE" = "false" ]; then PATH_ENC="%2Fvaults%2Freal-vault"; else PATH_ENC="%2Fvaults%2Ftest-vault"; fi
    cat <<EOF > /usr/bin/obsidian
#!/bin/bash
# This wrapper is generated by init-vault.sh
exec /opt/obsidian/obsidian --no-sandbox "obsidian://open?path=$PATH_ENC" "\$@"
EOF
    chmod +x /usr/bin/obsidian

    # Set up Openbox autostart
    echo "xrandr --size 1280x720" > /config/.config/openbox/autostart
    echo "obsidian &" >> /config/.config/openbox/autostart
fi

lsiown -R abc:abc /vaults "$OBSIDIAN_CONFIG_DIR" "/config/.config/openbox"

echo "**** Init complete. ****"
